Fix: TreeBuilder Constructor for Symfony 5.1
Cethy/GooglePlaceAutocompleteBundle pull request #13
Opened 2020-11-24 10:10 UTC by skPink

Fix #12 

Modification of treeBuilder for Symfony 5.1 remove ->root() and replace on __construct of TreeBuilder

2020-11-24 10:10 UTC, skPink commented
@Cethy I make some modification for Treebuilder

2020-12-04 13:28 UTC, skPink commented
@Cethy I realy want this PR

2020-12-04 18:38 UTC, Cethy requested changes

2020-12-04 18:38 UTC, Cethy commented on src/DependencyInjection/Configuration.php
> +        $rootNode = $treeBuilder;
According to [this](https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes), it needs `->getRootNode()` to work.
Did you try it in this state ?

2020-12-04 21:14 UTC, skPink commented
@Cethy i update and add getRootNode()

2020-12-06 19:29 UTC, merged